version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver_db
    user: root
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=TuPasswordFuerte123
    ports:
      - "1433:1433"
    networks:
      - autos-net

  sqlserver-init:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver_init
    depends_on:
      - sqlserver
    command: >
      /bin/bash -c "
        echo 'Esperando a que SQL Server 2022 termine de iniciar...'
        sleep 20
        echo 'Comprobando conexión interna a SQL Server...'
        until /opt/mssql-tools18/bin/sqlcmd -S sqlserver,1433 -U sa -P TuPasswordFuerte123 -C -Q 'SELECT 1'; do
          echo 'El motor aún no responde... reintentando en 5 segundos...'
          sleep 5
        done
        echo '¡Autenticación exitosa! Procediendo a crear la base de datos...'
        /opt/mssql-tools18/bin/sqlcmd -S sqlserver,1433 -U sa -P TuPasswordFuerte123 -C -Q \"IF NOT EXISTS (SELECT * FROM sys.databases WHERE name = 'AutosManagementDB') BEGIN CREATE DATABASE AutosManagementDB; END\"
        echo 'Base de datos AutosManagementDB verificada/creada con éxito.'
      "
    networks:
      - autos-net

  user-auth-service:
    build: ./user-auth-service
    container_name: user-auth-service
    restart: on-failure
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:sqlserver://sqlserver_db:1433;databaseName=AutosManagementDB;encrypt=false
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=TuPasswordFuerte123
    depends_on:
      sqlserver-init:
        condition: service_completed_successfully
    networks:
      - autos-net

  autos-service:
    build: ./autos-service
    container_name: autos-service
    restart: on-failure
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:sqlserver://sqlserver_db:1433;databaseName=AutosManagementDB;encrypt=false
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=TuPasswordFuerte123
    depends_on:
      sqlserver-init:
        condition: service_completed_successfully
    networks:
      - autos-net

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      user-auth-service:
        condition: service_started
      autos-service:
        condition: service_started
    networks:
      - autos-net

  frontend:
    build:
      context: ./frontend-autos
      dockerfile: Dockerfile
    container_name: frontend-autos
    ports:
      - "4200:80"
    depends_on:
      - api-gateway
    networks:
      - autos-net

networks:
  autos-net:
    driver: bridge